# -*- coding: utf-8 -*-
"""mba_main (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MExmeFXT6PnKWnwbQH7I7HZnlBdd8mhV
"""

import pandas as pd

def RecommendItems(CurItemOfInterest, CustomerID, Country, Time, Date):
    data = pd.read_csv('cleaned.csv', low_memory=False)
    invo_no = data[(data['StockCode'] == CurItemOfInterest) &
                   (data['Country'] == Country) &
                   (data['date'] == Date)]['InvoiceNo'].tolist()

    filtered_data = data[data['InvoiceNo'].isin(invo_no)]

    item_cnt = filtered_data['StockCode'].value_counts().to_dict()

    # Extract top 10 items
    top_items = list(item_cnt.keys())[:min(10, len(item_cnt))]

    del data
    return top_items