# -*- coding: utf-8 -*-
"""bc_main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rMTPWTgYQ_3cnYqTk_y7U4X8nd7Yu7Px
"""

import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings('ignore')
import joblib

from google.colab import drive
drive.mount('/content/drive')

file_path = "dataset_b11.csv"

model_path = "model.pkl"

data = pd.read_csv(file_path,names=["class","values"])

rf_model = joblib.load(model_path)

def classify_b(value):
    # Predict the class for the input value
    class_label = rf_model.predict([[value]])[0]
    return class_label



